USE [guesterz]
GO

/****** Object:  Table [dbo].[UTILISATEUR]    Script Date: 29/10/2017 20:09:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UTILISATEUR](
	[ID_USER] [int] IDENTITY(1,1) NOT NULL,
	[PSEUDO] [nvarchar](50) NOT NULL,
	[NOM] [varchar](50) NOT NULL,
	[PRENOM] [varchar](50) NOT NULL,
	[DATE_NAISSANCE] [date] NOT NULL,
	[RATING_HOST] [decimal](9, 3) NOT NULL,
	[RATING_GUEST] [decimal](9, 3) NOT NULL,
	[PASSWORD] [nvarchar](50) NOT NULL,
	[LNK_PHOTO_PROFIL] [varchar](500) NOT NULL,
	[DESCRIPTION] [varchar](5000) NOT NULL,
	[MAIL] [varchar](100) NOT NULL,
	[VALIDE] [bit] NOT NULL,
	[DATE_VALIDATION] [datetime] NULL,
	[DATE_CREATION] [datetime] NOT NULL,
	[DATE_MODIFICATION] [datetime] NOT NULL,
 CONSTRAINT [PK_UTILISATEUR] PRIMARY KEY CLUSTERED 
(
	[ID_USER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[UTILISATEUR] ADD  CONSTRAINT [DF_UTILISATEUR_RATING_HOST]  DEFAULT ((0)) FOR [RATING_HOST]
GO

ALTER TABLE [dbo].[UTILISATEUR] ADD  CONSTRAINT [DF_UTILISATEUR_VALIDE]  DEFAULT ((0)) FOR [VALIDE]
GO

ALTER TABLE [dbo].[UTILISATEUR] ADD  CONSTRAINT [DF_UTILISATEUR_DATE_CREATION]  DEFAULT (getdate()) FOR [DATE_CREATION]
GO

ALTER TABLE [dbo].[UTILISATEUR] ADD  CONSTRAINT [DF_UTILISATEUR_DATE_MODIFICATION]  DEFAULT (getdate()) FOR [DATE_MODIFICATION]
GO
